//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAppDelSaver.h"

@implementation SCAppDelSaver

+ (id)albumWithTitle:(id)arg1 {
	NSPredicate *predicate = [NSPredicate predicateWithFormat:@"localizedTitle = %@", arg1];
	PHFetchOptions *fetchOptions = [[PHFetchOptions alloc] init];
	[fetchOptions setPredicate:predicate];
	PHFetchResult *results = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAlbumRegular options:fetchOptions];
	if ([results count]) {
		return [results objectAtIndex:0];
	}
	return nil;
}
+ (void)saveToPhotoLibraryWithImage:(id)arg1 orVideoURL:(id)arg2 withAssetCollection:(id)arg3 completion:(CDUnknownBlockType)arg4 {

}
+ (void)saveToPhotoLibraryWithImage:(id)arg1 orVideoURL:(id)arg2 albumName:(id)arg3 completion:(CDUnknownBlockType)arg4 {

}
+ (void)handleVideoSave:(id)arg1 fromController:(id)arg2 completion:(CDUnknownBlockType)arg3 {

}
+ (void)handleImageSave:(id)arg1 fromController:(id)arg2 completion:(CDUnknownBlockType)arg3 {

}
+ (void)showSaveAlertIfNeededForMediaType:(long long)arg1 controller:(id)arg2 saveBlock:(CDUnknownBlockType)arg3 {

}

@end

